### ISSUE TITLE
POOM payment not received

### ISSUE THREAD

**Issue by sunk818** [biblepay/biblepay-evolution#14] opened 2019-09-11 04:33 UTC
My CPK name used to be RubeGold, but I hope a hacker didn't hack BiblePay and change it to sunk without my permission. 

Anyway, I sponsored two children and sent 85k BBP x 2 to Todd @ CameroonONE ([Payment 1](https://chainz.cryptoid.info/bbp/tx.dws?fe1b20d8c986a22582d7e956a371c5e06a8eed4a9ac72c9d901a70150bfac7d0.htm
), [Payment 2](https://chainz.cryptoid.info/bbp/tx.dws?c58afbe45e38f4f861ac4a6fc0ac08dedb3bf1f194e5215b43c8c863c53cde01.htm) )

When I first ran sponsorchild (and before sending 85k BBP), `listchildren` showed -999 then changed to 40 under balance. I after I submitted payment 1 & 2, the value went from 40 to 0. Strangely, I showed up on Leaderboard though:

![image](https://user-images.githubusercontent.com/6989799/64668101-26ae4b00-d411-11e9-9c30-d191934ec19b.png)

Thinking I would get paid, I was expecting ~9k today from the Smart Contract Reward (~5k BBP for POOM and ~4k for healing). I only received ~4k which means the healing campaign paid out, but not the POOM payment.

```
21:21:37 listchildren
21:21:37￼
{
  "List Of": "Cameroon-One Children",
  "Child ID": "8bc83da6",
  "CPK": "BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU",
  "Biography": "https://biblepay.cameroonone.org/8bc83da6.htm",
  "Balance": 0,
  "Nickname": "RubeGold",
  "Child ID": "caffec51",
  "CPK": "BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU",
  "Biography": "https://biblepay.cameroonone.org/caffec51.htm",
  "Balance": 0,
  "Nickname": "RubeGold"
}
```

**Comment by biblepay** [comment] 2019-09-11 14:44
I sent you an e-mail regarding Rube, please reply to that first.

**Comment by biblepay** [comment] 2019-09-11 14:46
Question on Rube:  You had a prayer in for healing that you prayed for the dead Texas postal worker, but you live in LA.  You said "he was my mailman".  How was he your mailman?

**Comment by sunk818** [comment] 2019-09-11 18:22
@biblepay I replied to your e-mail days ago (although I'm not sure it is relevant to the specific issue, or is it?).  "he was my mailman" -- please don't take it literally. The postal worker that delivers mail. He is literally not my mailman, but he is everyone's mailman. It is a method to personalize an event so it is more meaningful. The prayer had multiple carriage lines so perhaps the rest of the prayer got cut off.

If you have contention with this, are you implying that you are able to withhold payment for POOM even though I've donated to CameroonONE for two orphans already plus 50k BBP x 2 to authorize sponsorship of children? 

Plus I've written three articles already about POOM: https://whitewalr.us/biblepay

**Comment by biblepay** [comment] 2019-09-11 18:53
So, Sun, why was your nickname Rube, can you explain the reasoning behind that mean spirited nickname?  (Being that your name is Sun, and you are not an inventor, why RubeGold?)

Yes, its relevant to know these answers first, in order to help diagnose your "potential problem" (that  does not appear to be a "problem").

I believe you are being dishonest now- you didn't reply to my email and now you erased the comment that you replied to my email.

Lets look at this prayer:
"prayed for gary's knee paind.  went from 5 to 7."  Isnt this mocking Christianity?  It doesnt even have capitalization and its misspelled.  Did you really pray for a Gary, and his knee got worse?  No, I think you are trying to be funny by mocking us.  (I PRAYED FOR GARY THAT DAY!  And you took my pain numbers and reversed them!)  The reason I say that is there are many prayers you entered that mock and scoff at Christianity.

What Im alluding to is I believe, from what I see, as I uncover each prayer that we should enter a ticket to clawback our BBP back from you.

We didn't create a HEALing campaign to be taken advantage of (by you stealing from us) and making fun of Christians at the same time (making a mockery of our system).  I am leaning towards thinking you owe us these healing payments.

If you want to reply to my email first that I sent days ago lets discuss the healing issue first and lets discuss your replies.  Point being, if you don't have a valid CPK, you don't generate POOM rewards either.  

As far as remaining civil, I have not changed Sun.  You will have to consider controlling your temper, repenting of your sins and being honest.  At one point you accused me of being a fake Christian and that was very hurtful Sun.  I forgave you of that, but I Did expect an apology.

**Comment by sunk818** [comment] 2019-09-11 19:11
> why RubeGold?

I love the videos on YouTube where people make contraptions. 

> trying to be funny by mocking

Yes, I agree, perhaps that was in poor attempt at humor. 

I've since gotten advice from oncoapop3 and he's helped me make my prayers more meaningful.

**Comment by biblepay** [comment] 2019-09-11 22:33
Ok, so looking at this POOM payment issue:

You have to wait for the following superblock *after* your first payment.  So, if you just made these two payments (I see the block paid was less than 24 hours ago), your reward will start regularly as of the next superblock.

Type:
leaderboard true 143935

And you should see 2667 for POOM as of today, meaning as of the block 143935+205 you will receive the actual reward listed (it might be off by 1% due to rounding issues).

If your POOM balance is 0, thats OK, that counts as a credit (IE rewards occur when balances are 0 or lower).

So everything looks OK.

Please let me know if you are happy and if we can close this.

**Comment by sunk818** [comment] 2019-09-17 01:44
> My CPK name used to be RubeGold

Do you know how my CPK can go back to being RubeGold? 

In details, it shows Sunk but in ALL in shows RubeGold

**Comment by sunk818** [comment] 2019-09-19 05:15
Do you know what the following values mean under balance?

I notice only BBP reward is made when balance is 0.

-999
0
40

**Comment by sunk818** [comment] 2019-09-24 16:05
I don't see POOM payment just now. GSC Transmission sent for CameroonONE on these blocks for me:

Height: 146951
Height: 146946
Height: 146830

```
19:01:01 |   | leaderboard Sunk 147005
19:01:02 |   | {   "Prominence v1.1": "Details",   "CAMEROON-ONE: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",   "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 7364778.00": "1.14%",   "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",   "Healing": "Diary Entries",   "Sunk": "prayed for healing of the marriage of m/m after discovery of infidelity. may they grow stronger together discover the forgiveness and healing power of Jesus",   "Prominence": "Totals",   "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 7364778.00, Reward: 3886.440": "1.140%" }
```

**Comment by biblepay** [comment] 2019-09-28 18:53
@sunk818 
1) Multiple wallets are OK, as long as one is sending an official Cameroon-One transmission per day.
2) Sending more than one transmission per day for Cameroon is OK.  We will only regard one as valid.
3) Not sure what you mean by "no tithe went to BB2".  The GSC system requires you to either leave the miner running, *or* type 'sengscc cameroon-one 1' once per day.
4) Could you please paste the output of 'exec sentgsc'.  Lets see that so we can look at the transmissions within the 24 hour period that correspond to the 'leaderboard Sunk 147005's height.

**Comment by biblepay** [comment] 2019-09-28 19:56
On my above post, let me clarify # 3, where you said you didnt Tithe to BB2 in the Cameroon transaction.  I investigated our code, to ensure we dont require a tithe on cameroon (IE, maybe it was possible we skipped zero tithes) - but anyway, no we don't require tithes on cameroons.  If we see a GSC transmission with zero tithe, but its to cameroon, we accept it.    So you are ok in that case anyway.

Moving on to this particular days missing payment, I went ahead and modified the 'exec sentgsc' RPC command to take the CPK and the leaderboard superblock payment height, in case we want to check other cpks.

Here is your CPKs output for that days range.  On a side note, a leaderboard superblock height of 147005 includes GSC transmissions from height 146595 through 146799.  I also added the "range" of the leaderboard into the "leaderboard" RPC output for the next version, so you can see the range easily from the rpc.

So here is the output of exec sentgsc your_cpk 147005 (for range 146595-146799):

  "bcd9fbf7971361526e880c21b634f476d95cf1761dd60079dac5d1bbcbe8669c": "ABN Weight: 192420.71, Height: 146630, Date: 09-22-2019 21:47:40",
  "9eea7f93bd62057c21aaf7bf4f6e63c21b1ad734e3aa85f2f965269497f01ee0": "ABN Weight: 178337.48, Height: 146652, Date: 09-23-2019 00:00:48",
  "fabbb04ec0447e362b79048fc87291645125cad68eb3d8878de16e7d7a3795bd": "ABN Weight: 231295.37, Height: 146675, Date: 09-23-2019 02:37:29",
  "90a97056461e1e5666f4983dce30bfc44edee4e5148cc849bbf80e65ddaae0f2": "Points: 7364778, Campaign: HEALING, CoinAge: 7364778, Donation: 1.00, Height: 146687, Date: 09-23-2019 04:04:06",
  "72c6246aa525e81eb8b79b45c80a9f957ae8074f647fb7db7638da872b3da949": "ABN Weight: 130246.27, Height: 146722, Date: 09-23-2019 07:53:27",


Notice how there are No cameroon transmissions in that 205 block range.

You have 4 ABN hits that day and one healing; that explains the single healing payment in the superblock.

**Comment by sunk818** [comment] 2019-09-30 17:38
> Multiple wallets are OK, as long as one is sending an official Cameroon-One transmission per day.

I figured out that two wallets were transmitting GSC for CameroonONE. I had `disablegsctransmission=1` but the `biblepay.conf` was corrupted with line ending being CR only (Macintosh) instead of CRLF. So, my settings were ignored. 146951 donated 1.777 BBP CameroonONE, but 26 minutes later 146951 donated 0. So, my thought is that whatever the last GSC transmission is for CameroonONE is the one that got processed. I think as long as my biblepay.conf doesn't get corrupted, the `biblepay.conf` parameters should be observed. Once I resaved biblepay.conf for line ending CRLF, this issue went away (only have one wallet send gsc tx).

this is `exec sentgsc`

```
{
  "af71362b8e3a382628ac91150e8f2a917ee39262945e7846cea761e979a99e8b": "ABN Weight: 175885.97, Height: 146891, Date: 09-24-2019 03:08:33",
  "3fe81948673d12c27713b67667eea82f51973c96591948c26fee978713b27af3": "ABN Weight: 136160.88, Height: 146893, Date: 09-24-2019 03:21:49",
  "48e56b6080b63deb837897c82c268805f1b6473e20d741bd8689736f2c55abb8": "Points: 6128765, Campaign: HEALING, CoinAge: 6128765, Donation: 1.78, Height: 146909, Date: 09-24-2019 05:15:27",
  "89e5b1c3879050c7f2164fe1ed8cb0c9a781f528044f65b7bdc3e4dc50a07f62": "Points: 0, Campaign: CAMEROON-ONE, CoinAge: 822, Donation: 1.78, Height: 146946, Date: 09-24-2019 09:16:51",
  "1a50ca538ee6546b42f6a3dea2205ddde0d501970779e6f92527a919dd3a0361": "Points: 0, Campaign: CAMEROON-ONE, CoinAge: 692, Donation: 0.00, Height: 146951, Date: 09-24-2019 09:51:52",
  "6e7eb6206f1635f37df5037673c12829c71e384d50e711df0639103a381822ec": "ABN Weight: 144031.45, Height: 146957, Date: 09-24-2019 10:34:27",
  "5073bf9c185ddc9a16ac7d6b1b27c7efc5ca7e347d74c86e09f3924317c1ac89": "Points: 2821348, Campaign: HEALING, CoinAge: 2821348, Donation: 2.78, Height: 147005, Date: 09-24-2019 15:52:22",
```

this is leaderboard Sunk 147005

```
{
  "Prominence v1.1": "Details",
  "Block Range": "146595-146800",
  "HEALING: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 7364778.00": "1.14%",
  "POG: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 0.00": "0.00%",
  "Healing": "Diary Entries",
  "Sunk": "prayed for healing xxx",
  "Prominence": "Totals",
  "ALL: BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU [Sunk], Pts: 7364778.00, Reward: 3886.440": "1.140%"
}
```

**Comment by sunk818** [comment] 2019-10-01 16:13
On `"Child ID": "77563464"` Todd said, 

> "It is showing correctly input on our end. I just re-uploaded 
> the main file that reflects correctly. Let's see if it adjusts."

Would you happen to know why the sponsored child is showing a balance of 40?

```
"Child ID": "77563464",
  "CPK": "BLENRYgVPwzfsrJoJNbvC537qMHsCVyeFU",
  "Biography": "https://biblepay.cameroonone.org/bios/77563464.htm",
  "Balance": 40,
  "Nickname": "xxxx",
```

**Comment by biblepay** [comment] 2019-10-01 23:01
It looks like 77563464 has two $40 charges  (9-17, and 9-23)  and one $40 payment.  That means this child would have a $40.00 balance.  I assume the problem is you want one $40 charge in September?  Would you like me to ask Todd to remove the 9-23 charge?  The reason I ask is I assume Todd has not charged $40 for October yet (based on the date of the charge).

Let me know if you want me to reach out to him or if you are reaching?

**Comment by sunk818** [comment] 2019-10-01 23:43
I was told a balance of 40 means that $40 is due. It showed up as balance of 0 (all paid up for month), but then it changed to 40 a day or two later. If you can help, that's great. I just was not sure who needs to review or make the adjustments.

ChildID: 007c26f3
To: Todd @ CameroonONE BHRiFZYUpHj2r3gxw7pHyvByTUk1dGb8vz
Debit: -70 468.96140480 BBP
Transaction ID: [3041ba1025c0b6031472077a3644c13899db7446ba9ad3cd0afc95c78faa5605](https://chainz.cryptoid.info/bbp/tx.dws?3041ba1025c0b6031472077a3644c13899db7446ba9ad3cd0afc95c78faa5605.htm)


ChildID: 77563464
To: Todd @ CameroonONE BHRiFZYUpHj2r3gxw7pHyvByTUk1dGb8vz
Debit: -70 467.96140480 BBP
Transaction ID: [021e197c2fa05a7d3478bb3ac2f4c0b666d9460eca52b62bb8f3661d7ef0af14](https://chainz.cryptoid.info/bbp/tx.dws?021e197c2fa05a7d3478bb3ac2f4c0b666d9460eca52b62bb8f3661d7ef0af14.htm)

**Comment by biblepay** [comment] 2019-10-02 13:02
So to summarize:  
Your poom payment was not received because your GSC was not sent.

Your POOM child balance is correct - you currently owe $40.00 based on the charges entered.

A balance of -999 means child is not provisioned.  No poom rewards are paid.
A negative balance or a zero balance means you are in good standing and you are owed poom rewards.
A positive balance means you owe Cameroon and are not applicable for poom rewards.

For transaction history, please see Cameroons payment history interface - as this is your personal sponsored child (the child is not sponsored with BiblePay).

**Closed by biblepay** 2019-10-02 13:02 UTC
